create_clock -period 2.857 -name CLK -waveform {0.000 1.429} [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports EMPTY]
set_property IOSTANDARD LVCMOS33 [get_ports FULL]
set_property IOSTANDARD LVCMOS33 [get_ports READ]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports WRITE]
